name: Run tests

on:
  workflow_dispatch:  # manual
  pull_request:
    branches: [ main ]

jobs:
  mac-tests:
    name: Run tests on Mac
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install package and dependencies
      run: |
        python3 -m pip install -e .[tests]
    
    - name: Run tests
      run: |
        pytest
  
  windows-tests:
    name: Run tests on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install package and dependencies
      run: |
        python3 -m pip install -e .[tests]
    
    - name: Run tests
      run: |
        pytest
    
  linux-tests:
    name: Run tests on Linux
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4
    
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"
        
        - name: Prepare to build wx
          run: |
            python3 -m pip install wheel six distro attrdict3
            sudo apt-get update
            sudo apt-get install -y -qq python3-dev libgtk-3-dev
            sudo apt-get install -y -qq libgstreamer1.0-0 gstreamer1.0-plugins-base
            sudo apt-get install -y -qq libwebkit2gtk-4.0-dev
            sudo apt-get install -y -qq libpng-dev libjpeg-dev libtiff-dev libnotify-dev libsm-dev
            sudo apt-get install -y -qq libsdl2-dev libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-2.
        
        - name: Install package and dependencies
          run: |
            python3 -m pip install -e .[tests]
        
        - name: Run tests
          run: |
            pytest